channels:
- conda-forge
- defaults
- conda-forge/label/broken
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- aiobotocore=2.24.0
- aiohappyeyeballs=2.6.1
- aiohttp=3.12.15
- aioitertools=0.12.0
- aiosignal=1.4.0
- alembic=1.14.1
- annotated-types=0.7.0
- anyio=4.8.0
- argon2-cffi=23.1.0
- argon2-cffi-bindings=21.2.0
- arrow=1.3.0
- asttokens=3.0.0
- async-lru=2.0.4
- async_generator=1.10
- attr=2.5.1
- attrs=25.1.0
- aws-c-auth=0.9.0
- aws-c-cal=0.9.2
- aws-c-common=0.12.4
- aws-c-compression=0.3.1
- aws-c-event-stream=0.5.5
- aws-c-http=0.10.4
- aws-c-io=0.21.2
- aws-c-mqtt=0.13.3
- aws-c-s3=0.8.6
- aws-c-sdkutils=0.2.4
- aws-checksums=0.2.7
- aws-crt-cpp=0.33.1
- aws-sdk-cpp=1.11.606
- azure-core-cpp=1.16.0
- azure-identity-cpp=1.12.0
- azure-storage-blobs-cpp=12.14.0
- azure-storage-common-cpp=12.10.0
- azure-storage-files-datalake-cpp=12.12.0
- babel=2.17.0
- beautifulsoup4=4.13.3
- bias_correction=0.4
- bleach=6.2.0
- bleach-with-css=6.2.0
- blinker=1.9.0
- blosc=1.21.6
- bokeh=3.7.3
- boltons=25.0.0
- botocore=1.39.11
- bottleneck=1.5.0
- brotli=1.1.0
- brotli-bin=1.1.0
- brotli-python=1.1.0
- bzip2=1.0.8
- c-ares=1.34.5
- ca-certificates=2025.1.31
- cached-property=1.5.2
- cached_property=1.5.2
- cachetools=5.5.2
- cartopy=0.25.0
- certifi=2024.12.14
- certipy=0.2.1
- cf_xarray=0.10.7
- cffi=1.17.1
- cftime=1.6.4
- charset-normalizer=3.4.1
- click=8.2.1
- climpred=2.5.0
- cloudpickle=3.1.1
- comm=0.2.2
- contourpy=1.3.3
- crc32c=2.7.1
- cryptography=44.0.0
- curl=8.14.1
- cycler=0.12.1
- cytoolz=1.0.1
- dask=2025.7.0
- dask-core=2025.7.0
- debugpy=1.8.12
- decorator=5.1.1
- defusedxml=0.7.1
- deprecated=1.2.18
- distributed=2025.7.0
- docrep=0.3.2
- donfig=0.8.1.post1
- eofs=2.0.0
- esmf=8.9.0
- esmpy=8.9.0
- exceptiongroup=1.2.2
- executing=2.1.0
- filelock=3.19.1
- flexcache=0.3
- flexparser=0.4
- fonttools=4.59.1
- fqdn=1.5.1
- freetype=2.13.3
- frozenlist=1.7.0
- fsspec=2025.7.0
- future=1.0.0
- gcsfs=2025.7.0
- geos=3.13.1
- gflags=2.2.2
- glog=0.7.1
- google-api-core=2.25.1
- google-auth=2.40.3
- google-auth-oauthlib=1.2.2
- google-cloud-core=2.4.3
- google-cloud-storage=3.3.0
- google-crc32c=1.7.1
- google-resumable-media=2.7.2
- googleapis-common-protos=1.70.0
- greenlet=3.1.1
- grpcio=1.73.1
- h11=0.14.0
- h2=4.2.0
- hdf4=4.2.15
- hdf5=1.14.6
- hpack=4.1.0
- httpcore=1.0.7
- httpx=0.28.1
- hyperframe=6.1.0
- icu=75.1
- idna=3.10
- importlib-metadata=8.6.1
- importlib_resources=6.5.2
- ipykernel=6.29.5
- ipython=8.32.0
- ipython_pygments_lexers=1.1.1
- ipywidgets=8.1.5
- isoduration=20.11.0
- jedi=0.19.2
- jinja2=3.1.5
- jmespath=1.0.1
- joblib=1.5.1
- json5=0.10.0
- jsonpickle=4.1.1
- jsonpointer=3.0.0
- jsonschema=4.23.0
- jsonschema-specifications=2024.10.1
- jsonschema-with-format-nongpl=4.23.0
- jupyter=1.1.1
- jupyter-lsp=2.2.5
- jupyter-offlinenotebook=0.3.1
- jupyter-resource-usage=1.1.0
- jupyter_client=8.6.3
- jupyter_console=6.6.3
- jupyter_core=5.7.2
- jupyter_events=0.12.0
- jupyter_server=2.15.0
- jupyter_server_terminals=0.5.3
- jupyterhub-base=5.2.1
- jupyterhub-singleuser=5.2.1
- jupyterlab=4.3.5
- jupyterlab_pygments=0.3.0
- jupyterlab_server=2.27.3
- jupyterlab_widgets=3.0.13
- keyutils=1.6.1
- kiwisolver=1.4.9
- krb5=1.21.3
- lark=1.2.2
- lcms2=2.17
- ld_impl_linux-64=2.43
- lerc=4.0.0
- libabseil=20250512.1
- libaec=1.1.4
- libarrow=21.0.0
- libarrow-acero=21.0.0
- libarrow-compute=21.0.0
- libarrow-dataset=21.0.0
- libarrow-substrait=21.0.0
- libblas=3.9.0
- libbrotlicommon=1.1.0
- libbrotlidec=1.1.0
- libbrotlienc=1.1.0
- libcap=2.75
- libcblas=3.9.0
- libcrc32c=1.1.2
- libcurl=8.14.1
- libdeflate=1.24
- libedit=3.1.20250104
- libev=4.33
- libevent=2.1.12
- libexpat=2.6.4
- libfabric=2.2.0
- libfabric1=2.2.0
- libffi=3.4.2
- libfreetype=2.13.3
- libfreetype6=2.13.3
- libgcc=15.1.0
- libgcc-ng=15.1.0
- libgcrypt-lib=1.11.1
- libgfortran=15.1.0
- libgfortran5=15.1.0
- libgomp=15.1.0
- libgoogle-cloud=2.39.0
- libgoogle-cloud-storage=2.39.0
- libgpg-error=1.55
- libgrpc=1.73.1
- libhwloc=2.12.1
- libiconv=1.18
- libjpeg-turbo=3.1.0
- liblapack=3.9.0
- liblzma=5.8.1
- libnetcdf=4.9.2
- libnghttp2=1.64.0
- libnl=3.11.0
- libnsl=2.0.1
- libopenblas=0.3.30
- libopentelemetry-cpp=1.21.0
- libopentelemetry-cpp-headers=1.21.0
- libparquet=21.0.0
- libpnetcdf=1.14.1
- libpng=1.6.50
- libprotobuf=6.31.1
- libre2-11=2025.07.22
- libsodium=1.0.20
- libsqlite=3.48.0
- libssh2=1.11.1
- libstdcxx=15.1.0
- libstdcxx-ng=15.1.0
- libsystemd0=257.7
- libthrift=0.22.0
- libtiff=4.7.0
- libudev1=257.7
- libutf8proc=2.10.0
- libuuid=2.38.1
- libuv=1.50.0
- libwebp-base=1.6.0
- libxcb=1.17.0
- libxcrypt=4.4.36
- libxml2=2.13.8
- libzip=1.11.2
- libzlib=1.3.1
- llvmlite=0.44.0
- locket=1.0.0
- lz4=4.4.4
- lz4-c=1.10.0
- mako=1.3.9
- markupsafe=3.0.2
- matplotlib-base=3.10.5
- matplotlib-inline=0.1.7
- mistune=3.1.1
- mpi=1.0.1
- mpich=4.3.1
- msgpack-python=1.1.1
- multidict=6.6.3
- munkres=1.1.4
- narwhals=2.1.2
- nbclient=0.10.2
- nbconvert-core=7.16.6
- nbformat=5.10.4
- nc-time-axis=1.4.1
- nccmp=1.10.0.0
- ncurses=6.5
- nest-asyncio=1.6.0
- netcdf-fortran=4.6.2
- netcdf4=1.7.2
- nlohmann_json=3.12.0
- nodejs=20.18.1
- notebook=7.3.2
- notebook-shim=0.2.4
- numba=0.61.2
- numcodecs=0.16.1
- numpy=1.26.4
- oauthlib=3.2.2
- openjpeg=2.5.3
- openssl=3.5.2
- orc=2.2.0
- overrides=7.7.0
- packaging=24.2
- pamela=1.2.0
- pandas=2.3.1
- pandocfilters=1.5.0
- parallelio=2_6_6
- parso=0.8.4
- partd=1.4.2
- patsy=1.0.1
- pexpect=4.9.0
- pickleshare=0.7.5
- pillow=11.3.0
- pint=0.25
- pip=25.0
- pkgutil-resolve-name=1.3.10
- platformdirs=4.3.6
- pooch=1.8.2
- proj=9.5.1
- prometheus-cpp=1.3.0
- prometheus_client=0.21.1
- prompt-toolkit=3.0.50
- prompt_toolkit=3.0.50
- propcache=0.3.1
- properscoring=0.1
- proto-plus=1.26.1
- protobuf=6.31.1
- psutil=5.9.8
- pthread-stubs=0.4
- ptyprocess=0.7.0
- pure_eval=0.2.3
- pyarrow=21.0.0
- pyarrow-core=21.0.0
- pyasn1=0.6.1
- pyasn1-modules=0.4.2
- pycparser=2.22
- pydantic=2.0.3
- pydantic-core=2.3.0
- pygments=2.19.1
- pyjwt=2.10.1
- pyopenssl=25.1.0
- pyparsing=3.2.3
- pyproj=3.7.1
- pyshp=3.0.0
- pysocks=1.7.1
- pyspharm=1.0.9
- python=3.11.11
- python-dateutil=2.9.0.post0
- python-fastjsonschema=2.21.1
- python-json-logger=2.0.7
- python-tzdata=2025.2
- python_abi=3.11
- pytz=2025.1
- pyu2f=0.1.5
- pyyaml=6.0.2
- pyzmq=26.2.1
- qhull=2020.2
- rdma-core=58.0
- re2=2025.07.22
- readline=8.2
- referencing=0.36.2
- requests=2.32.3
- requests-oauthlib=2.0.0
- rfc3339-validator=0.1.4
- rfc3986-validator=0.1.1
- rfc3987-syntax=1.1.0
- rpds-py=0.22.3
- rsa=4.9.1
- s2n=1.5.23
- s3fs=2025.7.0
- scikit-learn=1.7.1
- scipy=1.16.1
- send2trash=1.8.3
- setuptools=75.8.0
- shapely=2.1.1
- six=1.17.0
- snappy=1.2.2
- sniffio=1.3.1
- sortedcontainers=2.4.0
- soupsieve=2.5
- sparse=0.17.0
- sqlalchemy=2.0.38
- sqlite=3.48.0
- stack_data=0.6.3
- statsmodels=0.14.5
- tblib=3.1.0
- terminado=0.18.1
- threadpoolctl=3.6.0
- tinycss2=1.4.0
- tk=8.6.13
- tomli=2.2.1
- toolz=1.0.0
- tornado=6.4.2
- traitlets=5.14.3
- types-python-dateutil=2.9.0.20241206
- typing-extensions=4.12.2
- typing_extensions=4.12.2
- typing_utils=0.1.0
- tzdata=2025a
- ucx=1.19.0
- unicodedata2=16.0.0
- uri-template=1.3.0
- urllib3=2.3.0
- wcwidth=0.2.13
- webcolors=24.11.1
- webencodings=0.5.1
- websocket-client=1.8.0
- wheel=0.45.1
- widgetsnbextension=4.0.13
- wrapt=1.17.3
- xarray=2025.8.0
- xclim=0.57.0
- xesmf=0.8.10
- xhistogram=0.3.2
- xorg-libxau=1.0.12
- xorg-libxdmcp=1.1.5
- xrft=1.0.1
- xskillscore=0.0.27
- xyzservices=2025.4.0
- yamale=5.3.0
- yaml=0.2.5
- yarl=1.20.1
- zarr=3.1.1
- zeromq=4.3.5
- zict=3.0.0
- zipp=3.21.0
- zlib=1.3.1
- zstandard=0.23.0
- zstd=1.5.7
name: sfs_analysis_py311
